name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore plan-zajec-uczelnia/plan-zajec-uczelnia.csproj

      - name: Build
        run: dotnet build plan-zajec-uczelnia/plan-zajec-uczelnia.csproj --no-restore
